
name: Temp

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 14
        server-id: github
    - name: validate with Maven
      run: mvn -B validate --file pom.xml
    - name: compile with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B compile --file pom.xml
